### ISSUE TITLE
Dúvida

### ISSUE THREAD

**Issue by gkimura** [lazaropd/desafio-1-2-005#5]
Todos os tópicos utilizam os dados do arquivo csv. 
O ideal seria criarmos uma classe para todos usarem em seus exercicios, com um atributo que armazene o arquivo lido e uma função que faça essa leitura.
Querem que eu já comite essa classe?

**Comment by Alessandrabuso** [comment]
É muito bom para padronizar as entradas e saídas!
 Por favor, compartilha com a gente :)

**Comment by lazaropd** [comment]
Fiz um pequeno ajuste na classe de leitura de arquivos. 2 correçoes que foram necessarias ao executar no windows.
Na leitura do arquivo, adicionei o argumento de encoding=utf-8 e apliquei um strip('\n') na leitura das linhas para limpar o conteudo
