### ISSUE TITLE
Tópico 1: Quantidade de linhas com dados faltantes

### ISSUE THREAD

**Issue by gkimura** [lazaropd/desafio-1-2-005#6]
Requisitos:

Classe contendo:

- Atributo do tipo OBJETO (arquivo csv)  ou LISTA ( contém os dados do arquivo csv). Neste caso, a classe pode receber como atributo um objeto que contém a lista de dados, ou a lista diretamente.

- Função que itera entre as colunas do csv, contabiliza a quantidade de linhas com informações faltantes.

- Função retorna um valor float com a média dos dados faltantes por coluna.

**Comment by lazaropd** [comment]
Wana, sugiro criar tambem uma funcao para imprimir as médias de cada coluna, de uma forma mais visual. Algo assim talvez?
Nome coluna: xx% dados faltantes
Nome coluna2: xx% dados faltantes
Nome coluna 3 etc etc

**Comment by wbbatista** [comment]
done
