### ISSUE TITLE
Tópico 2: Nível taxônomico 

### ISSUE THREAD

**Issue by gkimura** [lazaropd/desafio-1-2-005#7]
Requisitos:

Classe contendo:

- Atributo do tipo OBJETO (arquivo csv) ou LISTA ( contém os dados do arquivo csv). Neste caso, a classe pode receber como atributo um objeto que contém a lista de dados, ou a lista diretamente.

- Função que verifica o intervalo de colunas que contém as informações dos níveis taxonômicos

- Para cada item do arquivo, função itera neste intervalo de colunas, verificando até qual nível taxonômico o item está registrado. 

- Função retorna um dicionário no formato  [ ID do item( número de linha ) ,  último nível taxonômica que está registrado ]

**Comment by gkimura** [comment]
Dúvida:

Agora que eu vi que já existe a coluna Nível Taxonômico, então talvez é só imprimí-la.

**Comment by lazaropd** [comment]
Criei uma coluna para nivel taxonomico embora ja houvesse essa coluna, para treinar mesmo.
A classe Lazaro retorna uma série de atributos da base de dados, seu uso está comentado ao longo do módulo.
